name: Deploy ECS App

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t log-analyzer .

      - name: Tag Image
        run: |
          docker tag log-analyzer:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push Image
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve